// <auto-generated />
using System;
using FoodTruck.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodTruck.Infrastructure.Migrations
{
    [DbContext(typeof(FoodTruckDbContext))]
    [Migration("20240520201100_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("FoodTruck.Domain.MobileFoodFacilities.MobileFoodFacility", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Approved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockLot")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cnn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaysHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirePreventionDistricts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodItems")
                        .HasColumnType("TEXT");

                    b.Property<int>("Latitude")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("Longitude")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Neighborhoods")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoliceDistricts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PriorPermit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Received")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupervisorDistricts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZipCodes")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationId");

                    b.ToTable("MobileFoodFacilities");
                });
#pragma warning restore 612, 618
        }
    }
}
