@FoodTruck.Api_HostAddress = http://localhost:5129

GET {{FoodTruck.Api_HostAddress}}/mobilefoodfacilities
Accept: application/json

###

GET {{FoodTruck.Api_HostAddress}}/mobilefoodfacilities/364218
Accept: application/json

###
